/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Model.People;
import Model.PeopleList;
import java.awt.Color;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Admin
 */
public class KbytDialog extends javax.swing.JFrame {

    /**
     * Creates new form victimForm
     */
    public KbytDialog() {
        initComponents();
    }
    
    PeopleList p1 = new PeopleList();

   
    public void fillDataTable(){
        DefaultTableModel model = (DefaultTableModel)table_people.getModel();
        model.setRowCount(0); //Clear table
        for(People peo:p1.getAllPeople()){
            Object rowData[] = new Object[9];
            rowData[0] = peo.getName();
            rowData[1] = peo.getAge();
            rowData[2] = peo.getGender();
            rowData[3] = peo.getNationality();
            rowData[4] = peo.getCccd();
            rowData[5] = peo.getPhoneNumber();
            rowData[6] = peo.getAddress();
            rowData[7] = peo.getVaccine();
            rowData[8] = peo.getNote();
            
            
            model.addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        Panel_Declare = new javax.swing.JPanel();
        Labell_Name = new javax.swing.JLabel();
        Labell_Age = new javax.swing.JLabel();
        Label_Gender = new javax.swing.JLabel();
        Label_CCCD = new javax.swing.JLabel();
        Label_Phone = new javax.swing.JLabel();
        Label_Address = new javax.swing.JLabel();
        Label_Note = new javax.swing.JLabel();
        Label_Nationality = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        txt_age = new javax.swing.JTextField();
        txt_cccd = new javax.swing.JTextField();
        txt_phone = new javax.swing.JTextField();
        txt_address = new javax.swing.JTextField();
        txt_note = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        btn_Update = new javax.swing.JButton();
        btn_Delete = new javax.swing.JButton();
        btn_Save = new javax.swing.JButton();
        btn_New = new javax.swing.JButton();
        txt_nationality = new javax.swing.JTextField();
        btnRadio_nam = new javax.swing.JRadioButton();
        btnRadio_nu = new javax.swing.JRadioButton();
        txt_vaccine = new javax.swing.JTextField();
        Label_VictimInfo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_people = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Khai báo y tế");

        Labell_Name.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Labell_Name.setText("Tên người khai: *");

        Labell_Age.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Labell_Age.setText("Tuổi: *");

        Label_Gender.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Label_Gender.setText("Giới tính: *");

        Label_CCCD.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Label_CCCD.setText("Số CCCD/Hộ chiếu: *");

        Label_Phone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Label_Phone.setText("Số điện thoại: *");

        Label_Address.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Label_Address.setText("Địa chỉ: *");

        Label_Note.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Label_Note.setText("Ghi chú:");

        Label_Nationality.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Label_Nationality.setText("Quốc tịch: *");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Số mũi Vaccine đã tiêm: *");

        txt_age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ageActionPerformed(evt);
            }
        });

        btn_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Search.png"))); // NOI18N
        btn_search.setText("Tìm kiếm");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        btn_Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Actions-document-edit-icon-16.png"))); // NOI18N
        btn_Update.setText("Cập nhật");
        btn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpdateActionPerformed(evt);
            }
        });

        btn_Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Actions-edit-delete-icon-16.png"))); // NOI18N
        btn_Delete.setText("Xóa");
        btn_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeleteActionPerformed(evt);
            }
        });

        btn_Save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Save-icon.png"))); // NOI18N
        btn_Save.setText("Lưu");
        btn_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SaveActionPerformed(evt);
            }
        });

        btn_New.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/new-icon-16.png"))); // NOI18N
        btn_New.setText("Nhập mới");
        btn_New.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NewActionPerformed(evt);
            }
        });

        txt_nationality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nationalityActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnRadio_nam);
        btnRadio_nam.setSelected(true);
        btnRadio_nam.setText("Nam");

        buttonGroup1.add(btnRadio_nu);
        btnRadio_nu.setText("Nữ");

        javax.swing.GroupLayout Panel_DeclareLayout = new javax.swing.GroupLayout(Panel_Declare);
        Panel_Declare.setLayout(Panel_DeclareLayout);
        Panel_DeclareLayout.setHorizontalGroup(
            Panel_DeclareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_DeclareLayout.createSequentialGroup()
                .addGroup(Panel_DeclareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_DeclareLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(Panel_DeclareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_DeclareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Labell_Name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Label_Gender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Label_CCCD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(Label_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(Panel_DeclareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_DeclareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(Panel_DeclareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_address, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_note, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txt_cccd, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Panel_DeclareLayout.createSequentialGroup()
                                .addComponent(btnRadio_nam)
                                .addGap(38, 38, 38)
                                .addComponent(btnRadio_nu)))
                        .addGap(21, 21, 21)
                        .addGroup(Panel_DeclareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_DeclareLayout.createSequentialGroup()
                                .addComponent(Label_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Panel_DeclareLayout.createSequentialGroup()
                                .addGroup(Panel_DeclareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Label_Nationality, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Labell_Age, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(Panel_DeclareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_age, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_nationality, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(Panel_DeclareLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(txt_vaccine, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(Panel_DeclareLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Panel_DeclareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_Note, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Panel_DeclareLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_New)
                                .addGap(18, 18, 18)
                                .addComponent(btn_Save, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_Update)
                                .addGap(18, 18, 18)
                                .addComponent(btn_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_DeclareLayout.setVerticalGroup(
            Panel_DeclareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_DeclareLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_DeclareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Labell_Name)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Labell_Age)
                    .addComponent(txt_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_DeclareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Gender)
                    .addComponent(Label_Nationality)
                    .addComponent(txt_nationality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRadio_nam)
                    .addComponent(btnRadio_nu))
                .addGap(18, 18, 18)
                .addGroup(Panel_DeclareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_CCCD)
                    .addComponent(txt_cccd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_Phone)
                    .addComponent(txt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Panel_DeclareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Address)
                    .addComponent(txt_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txt_vaccine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Panel_DeclareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Note)
                    .addComponent(txt_note, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Panel_DeclareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(Panel_DeclareLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(Panel_DeclareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Save, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Panel_DeclareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btn_Update)
                                .addComponent(btn_Delete)
                                .addComponent(btn_New)))))
                .addContainerGap())
        );

        Label_VictimInfo.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Label_VictimInfo.setForeground(new java.awt.Color(0, 0, 204));
        Label_VictimInfo.setText("THÔNG TIN KHAI BÁO Y TẾ");

        table_people.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Họ tên", "Tuổi", "Giới tính", "Quốc tịch", "CCCD", "SĐT", "Địa chỉ", "Vaccine", "Ghi chú"
            }
        ));
        table_people.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_peopleMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_people);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/qr_kbyt3.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("Quét mã tại đây để khai báo online");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(313, Short.MAX_VALUE)
                .addComponent(Label_VictimInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(260, 260, 260))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Panel_Declare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(Label_VictimInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Panel_Declare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void txt_ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ageActionPerformed

    private void txt_nationalityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nationalityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nationalityActionPerformed

    
    private void btn_NewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NewActionPerformed
        txt_name.setText("");
        txt_age.setText("");
        txt_cccd.setText("");
        txt_address.setText("");
        txt_nationality.setText("");
        txt_phone.setText("");
        txt_note.setText("");
    }//GEN-LAST:event_btn_NewActionPerformed

    public boolean validateForm(){
        if(txt_name.getText().isEmpty()||txt_cccd.getText().isEmpty()){
            return false;
        }
        return true;
    }
    
    public People getModel() throws ParseException{
        People peo = new People();
        peo.setName(txt_name.getText());
        peo.setAge(txt_age.getText());
        peo.setGender(btnRadio_nam.isSelected()? "Nam" : "Nữ");
        peo.setNationality(txt_nationality.getText());
        peo.setCccd(txt_cccd.getText());
        peo.setPhoneNumber(txt_phone.getText());
        peo.setAddress(txt_address.getText());
        peo.setNote(txt_note.getText());
//            peo.setVaccine((int) comboBox_vaccine.getSelectedItem());
        peo.setVaccine(txt_vaccine.getText());
        return peo;
    }
    
    public void setModel(People peo){
        //Đổ ngược dữ liệu từ bảng lên form
        txt_name.setText(peo.getName());
        txt_age.setText(peo.getAge());
//        peo.setGender(peo.isSelected()? "Nam" : "Nữ");
//        System.out.println(peo.getGender().equals("Nam"));
        if(peo.getGender().equals("Nam")){
            btnRadio_nam.isSelected();
            System.out.println("Checked");
        }else{
            btnRadio_nu.isSelected();
            System.out.println("Not");
        }
        txt_nationality.setText(peo.getNationality());
        txt_cccd.setText(peo.getCccd());
        txt_phone.setText(peo.getPhoneNumber());
        txt_address.setText(peo.getAddress());
        txt_note.setText(peo.getNote());
        txt_vaccine.setText(peo.getVaccine());

    }
    
    private void btn_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SaveActionPerformed
        StringBuilder sb = new StringBuilder();
        if(txt_cccd.getText().equals("")){
            sb.append("Căn cước công dân/ Hộ chiếu không được để trống!");
            txt_cccd.setBackground(Color.red);
        }else{
            txt_cccd.setBackground(Color.white);
        }
        if(sb.length() > 0){
            JOptionPane.showMessageDialog(this, sb);
            return;
        }
        
        try{
            People peo = getModel();
            PeopleList dao = new PeopleList();
            dao.insert(peo);
            
            JOptionPane.showMessageDialog(this, "Thông tin khai báo đã được lưu");
            fillDataTable(); //Thêm dữ liệu vào bảng
            
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_btn_SaveActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        // TODO add your handling code here:
        String id_search = txt_cccd.getText();
        if(id_search.isEmpty()){
            JOptionPane.showMessageDialog(this, "Nhập số CCCD của người bạn muốn tìm kiếm !");
        }else{
            People peo = p1.getPeopleByCccd(id_search);
            if(peo == null){
                JOptionPane.showMessageDialog(this, "Không tìm thấy người hợp lệ !");
            }else{
                setModel(peo);    
            }
        }                 
    }//GEN-LAST:event_btn_searchActionPerformed

    
    private void btn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpdateActionPerformed
        // TODO add your handling code here:
        if(validateForm()){
            try {
                People peo = getModel();
                if(p1.updatePeopleByCccd(peo)>0){
                    JOptionPane.showMessageDialog(this, "Cập nhật thành công");
                    fillDataTable();
                }
            } catch (Exception ex) {
                Logger.getLogger(KbytDialog.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }else{
            JOptionPane.showMessageDialog(this, "Thông tin chưa được nhập đầy đủ");
        }
    }//GEN-LAST:event_btn_UpdateActionPerformed

    private void btn_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeleteActionPerformed
        // TODO add your handling code here:
        if(txt_cccd.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập CCCD để xóa");
        }else{
            if(p1.delPeopleByID(txt_cccd.getText())>0){
                JOptionPane.showMessageDialog(this, "Xóa thành công");
                fillDataTable();
            }else{
                JOptionPane.showMessageDialog(this, "Không tìm thấy dữ liệu để xóa");
            }
        }
    }//GEN-LAST:event_btn_DeleteActionPerformed

    private void table_peopleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_peopleMouseClicked
        // TODO add your handling code here:
        int location = table_people.rowAtPoint(evt.getPoint());
        String cccd = table_people.getValueAt(location, 4).toString();
        People peo = p1.getPeopleByCccd(cccd);
        setModel(peo);
    }//GEN-LAST:event_table_peopleMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KbytDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KbytDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KbytDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KbytDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                KbytDialog kbyt = new KbytDialog();
                kbyt.fillDataTable();
                kbyt.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_Address;
    private javax.swing.JLabel Label_CCCD;
    private javax.swing.JLabel Label_Gender;
    private javax.swing.JLabel Label_Nationality;
    private javax.swing.JLabel Label_Note;
    private javax.swing.JLabel Label_Phone;
    private javax.swing.JLabel Label_VictimInfo;
    private javax.swing.JLabel Labell_Age;
    private javax.swing.JLabel Labell_Name;
    private javax.swing.JPanel Panel_Declare;
    private javax.swing.JRadioButton btnRadio_nam;
    private javax.swing.JRadioButton btnRadio_nu;
    private javax.swing.JButton btn_Delete;
    private javax.swing.JButton btn_New;
    private javax.swing.JButton btn_Save;
    private javax.swing.JButton btn_Update;
    private javax.swing.JButton btn_search;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable table_people;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_age;
    private javax.swing.JTextField txt_cccd;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_nationality;
    private javax.swing.JTextField txt_note;
    private javax.swing.JTextField txt_phone;
    private javax.swing.JTextField txt_vaccine;
    // End of variables declaration//GEN-END:variables
}
